Visitor can see products in different categories
CraftAcademy/slowfood-october-2019 pull request #3
Opened 2019-12-11 09:17 UTC by sundqvistjohan

[PT Link](https://www.pivotaltracker.com/story/show/170152670)
Adds category column to products database and validates presence of category in entries.
Adds headers for Starter/Main course/Dessert on menu and renders product under header based on category.

<img width="601" alt="Screenshot 2019-12-11 at 09 55 06" src="https://user-images.githubusercontent.com/56539700/70607775-5da61f80-1bff-11ea-9ba2-2a7589deeba4.png">

2019-12-11 15:16 UTC, sundqvistjohan commented
Changes from first revision of the pull request has been reverted. New model Category created with relation to Product.

2019-12-12 10:07 UTC, oliverochman requested changes

2019-12-12 10:07 UTC, oliverochman commented on spec/models/product_spec.rb
> -describe 'Factory' do
you need to test the association to category in this unit spec

2019-12-12 12:18 UTC, oliverochman approved these changes

2019-12-12 12:18 UTC, merged